name: gennis_innovative_school
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_slidable: ^3.0.0
  flutter_rating_bar: ^4.0.1
  scroll_date_picker: ^3.7.1
  logger: ^1.3.0
  motion_toast: ^2.6.7
  chucker_flutter: ^1.5.1
  cached_network_image: ^3.2.3
  shared_preferences: ^2.1.0
  drop_down_list_menu: ^0.0.9
  http: ^0.13.6
  get: ^4.6.5
  shimmer: ^3.0.0
  numberpicker: ^2.1.2
  cupertino_refresh: ^0.9.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
  - assets/images/

  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
