name: gennis_innovative_school
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_slidable: ^3.0.0
  flutter_rating_bar: ^4.0.1
  logger: ^1.3.0
  motion_toast: ^2.6.7
  shared_preferences: ^2.1.0
  http: ^0.13.6
  get: ^4.6.5
  #jwt_decoder: ^2.0.1
  connectivity_plus: ^4.0.1
  shimmer: ^3.0.0
  #cupertino_refresh: ^0.9.5
  animated_toggle_switch: ^0.7.0
  dio: ^5.3.2
  cached_network_image: ^3.2.3
  appinio_animated_toggle_tab: ^1.0.2
  date_time_picker: ^2.1.0
  image_picker: ^1.0.4
  material_dialogs: ^1.1.4
  roundcheckbox: ^2.0.5
  #liquid_pull_to_refresh: ^3.0.1
  #upgrader: ^8.1.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
  - assets/images/

  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
